server:
    port: 9191
spring:
    datasource:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
        password: password@123
        url: jdbc:sqlserver://javatechie-azure.database.windows.net:1433;database=javatechiedb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: javatechie
    jpa:
        show-sql: true
        
        